### ISSUE TITLE
The last version is not fully functional

### ISSUE THREAD

**Issue by eGameBuilders** [waccit/unified-red#113]
**Describe the bug**
When installing unified-red with npm or with node-red, the dashboard doesn't launch

**To Reproduce**
Install and see...

The "dir" folder is missing in the unified-red folder of node-modules of node-red directory.

You can take this of the unified-red 2.4, or compile it, but it's very hard with the new or old version of -red, npm or angular cli.

Is it possible to have a new compiled version of this folder in the next release?

**Comment by wac-eric** [comment]
We are well aware of the issue, I will keep you posted with new version addressing this bug.

**Comment by wac-dirka** [comment]
[eGameBuilders](https://github.com/eGameBuilders) We released version 2.5.2 today which resolves this issue. Thanks for reaching out to us about it!
