### ISSUE TITLE
[HELP] Initial Setup page forever

### ISSUE THREAD

**Issue by gponzo** [waccit/unified-red#20]
Sorry for bothering you here, but I can't find so much info on the web.

I just installed unified-red via Manage Palette and then I installed SQlite via apt.
Everytime I go on localhost:1800 I get the Initial Setup page.
I'd prefer to avoid MongoDB (at least on my personal PC used for dev and test). I don't know why it comes out every time, but from the only strange message on node-red console I guess it could be something regarding the DB connection. Here is the message:
```
(node:149970) [SEQUELIZE0003] DeprecationWarning: String based operators are deprecated. Please use Symbol based operators for better security, read more at https://sequelize.org/master/manual/querying.html#operators
(Use `node --trace-deprecation ...` to show where the warning was created)
```

I've tried both these connection strings but with no success:
`sqlite:node_modules/unified-red/unified-red.db`
(as suggested by the initial setup page) and
`sqlite:/home/gabriele/.node-red/unified-red/unified-red.db`

Is there some way to debug and understand what's the problem?
Thanks in advance!

**Comment by wac-dirka** [comment]
Hi gponzo,

It sounds like the Node-RED settings.js file is not being properly updated. Can you attach the file?

Also, I might need to setup a test environment to reproduce this. Can you provide the following information?
* Operating System: 
* Node.js version: 
* npm version: 
* Node-RED version: 
* Unified-RED version: 

Thanks!

**Comment by gponzo** [comment]
I'd better include the whole Node-RED log then:
```
2 Sep 18:16:03 - [info] Node-RED version: v1.3.5
2 Sep 18:16:03 - [info] Node.js  version: v14.17.6
2 Sep 18:16:03 - [info] Linux 5.4.0-81-generic x64 LE
2 Sep 18:16:03 - [info] Loading palette nodes
2 Sep 18:16:04 - [info] Unified-RED Dashboard version 2.0.8 started at /
2 Sep 18:16:04 - [info] Settings file  : /home/gabriele/.node-red/settings.js
2 Sep 18:16:04 - [info] HTTP Static    : /home/gabriele/.node-red/node_modules/unified-red/static
2 Sep 18:16:04 - [info] Context store  : 'default' [module=memory]
2 Sep 18:16:04 - [info] User directory : /home/gabriele/.node-red
2 Sep 18:16:04 - [info] Projects directory: /home/gabriele/.node-red/projects
(node:149970) [SEQUELIZE0003] DeprecationWarning: String based operators are deprecated. Please use Symbol based operators for better security, read more at https://sequelize.org/master/manual/querying.html#operators
(Use `node --trace-deprecation ...` to show where the warning was created)
2 Sep 18:16:05 - [info] Server now running at http://127.0.0.1:1880/admin/
2 Sep 18:16:05 - [info] Active project : unified-RED_Test
2 Sep 18:16:05 - [info] Flows file     : /home/gabriele/.node-red/projects/unified-RED_Test/flows_gabriele-Lenovo-IdeaPad-S340-14IIL.json
2 Sep 18:16:05 - [info] Starting flows
2 Sep 18:16:05 - [info] Started flows
```
npm version is 6.14.15
This is my settings file (renamed as TXT): [settings.js.txt](https://github.com/waccit/unified-red/files/7100852/settings.js.txt)

I've also disabled node-red-dashboard, in doubt it could conflict.
Thanks a lot for your kind support :)

**Comment by gponzo** [comment]
In the meanwhile I've noticed that two DB file has been created in the absolute specified position and in the .node-red/node_modules/unified-red directory.
They are both 53kB (full of what?!? :), so probably the problem is not in the DB connection as I thought.

**Comment by wac-dirka** [comment]
The issue is that adminAuth in settings.js isn’t being applied by our initial setup. We’ll get a hot fix rolled out for this. 

In the meanwhile you can manually set the adminAuth to this:
adminAuth: require("/home/gabriele/.node-red/node_modules/unified-red/admin-auth”),

**Comment by gponzo** [comment]
Thank you so much for the support and fix.
I don't know if I should report in another issue, but please notice that while registering at that login page, it rejected my email address as it has a "strange" domain like uname@xxx.yy.zz
My Gmail address was accepted instead.
