### ISSUE TITLE
[HELP] On a fresh install no widget appears, on my NoteBook button doesn't output anything

### ISSUE THREAD

**Issue by gponzo** [waccit/unified-red#23]
I'm very sorry to bother again. Please tell me if I or this place is not appropriate.

As in subject, I'm playing with unified-red and I composed a simple page on my NoteBook.
Text box seems to work, but the button doesn't output anything and the gauge doesn't display any number sent to it.

So I decided to try on another PC with a fresh install: the issue of my previous post (initial setup forever) didn't come out and it prompted me for a login, but now I've set up an even simpler page
![image](https://user-images.githubusercontent.com/63299644/132028324-d5e26035-5731-4400-adf8-5b01ef97cffc.png)
and nothing shows up :(
![image](https://user-images.githubusercontent.com/63299644/132027744-d908bd3f-bed2-44ab-baa4-eb502aeb2dbc.png)
[flows.json.txt](https://github.com/waccit/unified-red/files/7106865/flows.json.txt)
I attached the flow, while this is Node-RED's log:
```
3 Sep 17:01:25 - [info] 

Welcome to Node-RED
===================

3 Sep 17:01:25 - [info] Node-RED version: v2.0.6
3 Sep 17:01:25 - [info] Node.js  version: v14.17.6
3 Sep 17:01:25 - [info] Linux 5.4.0-80-generic x64 LE
3 Sep 17:01:25 - [info] Loading palette nodes
3 Sep 17:01:26 - [info] Unified-RED Dashboard version 2.0.9 started at /
3 Sep 17:01:26 - [info] Settings file  : /home/gabriele/.node-red/settings.js
3 Sep 17:01:26 - [info] HTTP Static    : /home/gabriele/.node-red/node_modules/unified-red/static
3 Sep 17:01:26 - [info] Context store  : 'default' [module=memory]
3 Sep 17:01:26 - [info] User directory : /home/gabriele/.node-red
3 Sep 17:01:26 - [warn] Projects disabled : editorTheme.projects.enabled=false
3 Sep 17:01:26 - [info] Flows file     : /home/gabriele/.node-red/flows.json
(node:189844) [SEQUELIZE0003] DeprecationWarning: String based operators are deprecated. Please use Symbol based operators for better security, read more at https://sequelize.org/master/manual/querying.html#operators
(Use `node --trace-deprecation ...` to show where the warning was created)
3 Sep 17:01:26 - [warn] 

---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.

If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.

You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------

3 Sep 17:01:26 - [info] Server now running at http://127.0.0.1:1880/admin/
3 Sep 17:01:26 - [info] Starting flows
3 Sep 17:01:26 - [info] Started flows
3 Sep 17:02:52 - [info] Stopping flows
3 Sep 17:02:52 - [info] Stopped flows
3 Sep 17:02:52 - [info] Starting flows
3 Sep 17:02:52 - [info] Started flows

```
Thanks a lot for your patience and support.

**Comment by wac-dirka** [comment]
gponzo, 

No problem however this is more of a discussion item. Would you be able to move this into our discussion forum? 

https://groups.google.com/g/unified-red

Also please include your flow file in the forum posting. That will help me see how each node is configured.

Samy
