### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by strbaknxp** [waccit/unified-red#45]
Hello I have an error: 
When I installed the Unified-red, Node-Red process stopped 10sec after installation, 
And each other start of node-red terminate after 10sec with this error: 
_23 May 16:26:53 - [info] nodes.flows.starting-flows
23 May 16:26:53 - [info] nodes.flows.started-flows
**Uncaught Exception
Operation `roles.findOne()` buffering timed out after 10000ms**_

I expect that its connected with mongoDB. I don't have installed it, but I would like to use sqlite or mariadb.
So I changed the config.json file with: sqlite:node_modules/unified-red/unified-red.db but it does not helped. 
I am not able do the configuration on the UI because the process kill itself with this error very fast. 

**Affected Environment (please select one or more):**
[x] Node-RED
[x] Unified-RED
[ ] Backend

**Context:**
Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.
* Operating System: Windows 10
* Node.js version: 16.13.2 -  32bit
* npm version: 8.5.4
* Node-RED version:2.1.2 
* Unified-RED version: 2.1.0

**Additional context**
I am running the Node-red as an extension of FreeMaster Lite. It is a NXP product. So I am not able to actualize any of components. 
Thank You
Pavol

**Comment by strbaknxp** [comment]
Now I was able to change the mongoDB to sqlite but it not create a DB in case it does not exist. 
So now It terminate with error: 
23 May 17:05:27 - [info] nodes.flows.starting-flows
23 May 17:05:27 - [info] nodes.flows.started-flows
**_Uncaught Exception
SQLITE_ERROR: no such table: Roles_**

Also, I found the bug, when it is changing the settings.js it add the:
 **_adminAuth: require("C:\Users\myPC\.node-red\node_modules\unified-red\admin-auth"),_** but the '\' is wrong. There should be added '\\' because its string, or '/'

Thank you 
Pavol

**Comment by wac-dirka** [comment]
Hi Pavol,

Thanks for your feedback.

We interface with the database using the Sequelize ORM package. Sequelize automatically generates tables (if they do not already exist) when we make a connection to the database. What version of Sequelize are you running? You can find this by running `npm list sequelize` from your node-red or unified-red folder.

Also, we have seen issues with Sequelize on Node 16. If possible, please try Node 14.

Did escaping backslash (\\) or replacing with forward slash (/) in the settings.js adminAuth property help?

**Comment by strbaknxp** [comment]
Hello, 

Thank you very much for response,
_node-red-project@0.0.1 C:\Users\nxf68958\.node-red
`-- unified-red@2.1.0 
     `-- sequelize@6.20.0_
I expect also that the package will create the database, but it does not. :-/
Unfortunately I am not able to reinstall it, because the FreeMaster Lite package does not support it. 

Yes, replacing backslash with two backslashes helped (C:\users\... -> C:\\users\\...). I did not tried forward slash, but I think It will worked also. :-)

**Comment by wac-dirka** [comment]
Resolved in version 2.2.1
