### ISSUE TITLE
ur_table help data not display

### ISSUE THREAD

**Issue by AimeeQiu** [waccit/unified-red#61]
**Describe the bug**
table data not display

**To Reproduce the flow**
[
    {
        "id": "ca1e4b39.d80c68",
        "type": "ur_table",
        "z": "d0d397e5.75c1d8",
        "tab": "8d4c377.380fcc8",
        "name": "",
        "order": 0,
        "width": "12",
        "height": 0,
        "label": "",
        "fields": [
            {
                "label": "name",
                "format": "{{msg.payload.name}}",
                "formatType": "text",
                "deviceType": "webApp",
                "device": "",
                "param": "name",
                "unitType": "unit",
                "unit": ""
            },
            {
                "label": "age",
                "format": "{{msg.payload.age}}",
                "formatType": "text",
                "deviceType": "webApp",
                "device": "",
                "param": "age",
                "unitType": "unit",
                "unit": ""
            },
            {
                "label": "birth",
                "format": "{{msg.payload.birth}}",
                "formatType": "text",
                "deviceType": "webApp",
                "device": "",
                "param": "birth",
                "unitType": "unit",
                "unit": ""
            }
        ],
        "cts": true,
        "topicPattern": "",
        "access": "",
        "accessBehavior": "hide",
        "x": 410,
        "y": 1040,
        "wires": []
    },
    {
        "id": "4fabff3a.a30cf",
        "type": "inject",
        "z": "d0d397e5.75c1d8",
        "name": "",
        "topic": "12",
        "payload": "[{\"name\":\"Kazuhito Yokoi\",\"age\":\"35\",\"birth\":\"12/09/1983\"},{\"name\":\"Oli Bob\",\"age\":\"12\",\"birth\":\"12/08/2017\"}]",
        "payloadType": "json",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 130,
        "y": 1040,
        "wires": [
            [
                "ca1e4b39.d80c68",
                "f3fa041b.f137c8"
            ]
        ]
    },
    {
        "id": "8d4c377.380fcc8",
        "type": "ur_tab",
        "z": "",
        "name": "表格",
        "order": 11,
        "group": "dee49b01.f44ec8",
        "disabled": false,
        "hidden": false,
        "access": "",
        "accessBehavior": "hide"
    },
    {
        "id": "dee49b01.f44ec8",
        "type": "ur_group",
        "z": "",
        "name": "画布1",
        "page": "c39635d4.ce60a8",
        "disp": true,
        "widthLg": "6",
        "widthMd": "6",
        "widthSm": "12",
        "disabled": false,
        "hidden": false,
        "access": "",
        "accessBehavior": "hide"
    },
    {
        "id": "c39635d4.ce60a8",
        "type": "ur_page",
        "z": "",
        "name": "组件概览",
        "folder": "9264531e.9b823",
        "order": 1,
        "disp": true,
        "width": 6,
        "disabled": false,
        "hidden": false,
        "access": "",
        "accessBehavior": "hide",
        "isMulti": false,
        "isSingle": true,
        "pageType": "single",
        "refPage": "none",
        "inheritInst": false,
        "expression": "",
        "instances": [
            {
                "names": {
                    "input": "",
                    "_arr": []
                },
                "param": {
                    "input": [],
                    "_arr": []
                }
            },
            {
                "names": {
                    "input": "",
                    "_arr": []
                },
                "param": {
                    "input": [],
                    "_arr": []
                }
            }
        ]
    },
    {
        "id": "9264531e.9b823",
        "type": "ur_folder",
        "z": "",
        "name": "管理后台",
        "icon": "dashboard",
        "disabled": false,
        "hidden": false,
        "access": "",
        "accessBehavior": "hide"
    }
]

**Context:**
Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.
* Operating System: ubuntu16.04
* Node.js version:  12.18.0
* npm version:  6.14.12
* Node-RED version:  1.0.6
* Unified-RED version:  2.3.0

**Comment by wac-mike** [comment]
AimeeQiu

Please see below:

[{"id":"ef9fec73c10d258f","type":"ur_table","z":"e3db398cb2b1ef6d","tab":"8d4c377.380fcc8","name":"","order":2,"width":0,"height":0,"label":"","fields":[{"label":"name","format":"{{msg.payload.name}}","formatType":"text","deviceType":"custom","device":"company/(.+)/(.*)","param":"person","unitType":"nothing","unit":""},{"label":"age","format":"{{msg.payload.age}}","formatType":"text","deviceType":"custom","device":"company/(.+)/(.*)","param":"person","unitType":"nothing","unit":""},{"label":"birth","format":"{{msg.payload.birth}}","formatType":"text","deviceType":"custom","device":"company/(.+)/(.*)","param":"person","unitType":"nothing","unit":""}],"cts":true,"topicPattern":"","access":"","accessBehavior":"","x":610,"y":160,"wires":[]},{"id":"4fabff3a.a30cf","type":"inject","z":"e3db398cb2b1ef6d","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"2","crontab":"","once":false,"onceDelay":0.1,"topic":"company/1/person","payload":"{\"name\":\"Kazuhito Yokoi\",\"age\":\"35\",\"birth\":\"12/09/1983\"}","payloadType":"json","x":330,"y":160,"wires":[["ef9fec73c10d258f"]]},{"id":"8425f6418229bc6d","type":"inject","z":"e3db398cb2b1ef6d","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"4","crontab":"","once":false,"onceDelay":0.1,"topic":"company/2/person","payload":"{\"name\":\"Oli Bob\",\"age\":\"12\",\"birth\":\"12/08/2017\"}","payloadType":"json","x":330,"y":200,"wires":[["ef9fec73c10d258f"]]},{"id":"8d4c377.380fcc8","type":"ur_tab","name":"General","order":11,"group":"dee49b01.f44ec8","disabled":false,"hidden":false,"access":"","accessBehavior":"hide"},{"id":"dee49b01.f44ec8","type":"ur_group","name":"Tab 1","page":"c39635d4.ce60a8","disp":true,"widthLg":"6","widthMd":"6","widthSm":"12","disabled":false,"hidden":false,"access":"","accessBehavior":"hide"},{"id":"c39635d4.ce60a8","type":"ur_page","name":"Group1","folder":"9264531e.9b823","order":1,"disp":true,"width":6,"disabled":false,"hidden":false,"access":"","accessBehavior":"hide","isMulti":false,"isSingle":true,"pageType":"single","refPage":"none","inheritInst":false,"expression":"","instances":[{"names":{"input":"","_arr":[]},"param":{"input":[],"_arr":[]}},{"names":{"input":"","_arr":[]},"param":{"input":[],"_arr":[]}}]},{"id":"9264531e.9b823","type":"ur_folder","name":"Table","icon":"dashboard","disabled":false,"hidden":false,"access":"","accessBehavior":"hide"}]

**Comment by AimeeQiu** [comment]
thank you @wac-mike, but I have a new problem,can you help me?
issue url : https://github.com/waccit/unified-red/issues/62
